### ISSUE TITLE
More GitHub Badges

### ISSUE THREAD

**Issue by wopian** [amio/badgen-service#101]
- [ ] Contributors
- [ ] Release downloads (total/latest)
- [ ] Last commit ![](https://img.shields.io/github/last-commit/wopian/hibari/new.svg)

**Comment by wopian** [comment]
@amio can this be re-opened 😄

**Comment by jneilliii** [comment]
@jackmu95, what are the requirements to get the release downloads to work?  It seems even the example on the badgen.net site is broken as it's displaying no assets.

**Comment by amio** [comment]
@jneilliii fixed in 30e19d0a07c14fa5fd49ef2345b57e9c0ef3394f, thanks for reporting ❤️
