### ISSUE TITLE
Internal Server error on npm downloads

### ISSUE THREAD

**Issue by olstenlarck** [amio/badgen-service#102]
I understand that my package kinda don't have downloads and/or api not refreshed yet, but would be better to show `dowloads/month | unknown` or such like that.

Otherwise badges are broken.

https://github.com/olstenlarck/flow-reporter-codeframe

**Comment by olstenlarck** [comment]
And actually.. We should try/catch all services, so NEVER BROKEN BADGES? :D

**Comment by amio** [comment]
If there's an live-fns error not caught, that's a bug 😅

**Comment by olstenlarck** [comment]
Btw, depending on `unpkg` for the "package" json stuff, makes problems with tht ecaching again ;d;d Their cache is bigger than our here, hm.

**Comment by amio** [comment]
Normally all exception should got caught in this [live-fetcher.js](https://github.com/amio/badgen-service/blob/ae833f43dfc2e0b08b04fbb7ad05e51b4ec94f0a/libs/live-fetcher.js#L8-L18), I'm not sure why it's 500 on server, on my local test it did response a `npm | unknown` badge. You can even throw as you wish in live-fns (if the `live-fetcher.js` works as I expected).

So basically no need to catch error in live functions unless we want to output some badge other than the default `<service-name> | unknown (grey)`. As this case, I think we can catch that 404 and return a normal badge `downloads | 0`:
```javascript
  const stats = await axios.get(endpoint.join('')).then(
    res => res.data,
    err => err.response.status === 404 && { downloads: 0 }
  )
```

**Comment by amio** [comment]
For the `unpkg` issue, maybe try `jsdelivr`?

**Comment by amio** [comment]
I figured where the Internal Server Error comes from, it's from [badgen api](https://api.badgen.net/npm/dw/flow-reporter-codeframe), not handled in `live-handlers.js`. This one on me. 😄

**Comment by olstenlarck** [comment]
The thing is that API does not returns 404? It's internal error so 500? :D 

Anyway, i've seen that updates take place, currently only the downloads/total is showing as `npm | not found`, but anyway.

Thanks.

**Comment by amio** [comment]
Total downloads needs counting separately, I forgot this in the first fix 😅
