### ISSUE TITLE
github "open issues" badge is red even if 0 issues open, should be green

### ISSUE THREAD

**Issue by papb** [amio/badgen-service#106]
I have a repo with 0 issues open. Unfortunately [it's badge shows in red](https://badgen.net/github/open-issues/papb/jsonify-error), which is discouraging.

Surely, where to draw the line between red/green is debatable, no question about it. But I'd say that 0 is a certain green.

Personally, 0 green and everything else red suits my needs, because my repo is small and I do intend to keep it on zero and will put a lot of effort on it!

**Comment by amio** [comment]
This color is "orange", I kinda like it (not a warning, but a warm welcome, personally feeling of course).

![](https://badgen.net/badge/color/red/red)
![](https://badgen.net/badge/color/orange/orange)
![](https://badgen.net/badge/color/green/green)

We definitely should give zero issue a big GREEN 👍
