### ISSUE TITLE
david-dm.org

### ISSUE THREAD

**Issue by amio** [amio/badgen-service#11]
## Docs

https://david-dm.org/

## Example

https://david-dm.org/zeit/pkg/
https://david-dm.org/zeit/pkg/info.json
https://david-dm.org/zeit/pkg/dev-info.json
https://david-dm.org/zeit/pkg/peer-info.json
https://david-dm.org/zeit/pkg/optional-info.json

**Comment by styfle** [comment]
This would be valuable to show dependencies and dev dependencies

**Comment by amio** [comment]
Finally got it works 
![](https://badgen.now.sh/david/dev/zeit/pkg)
![](https://badgen.now.sh/david/peer/zeit/pkg)
![](https://badgen.now.sh/david/optional/zeit/pkg)

**Comment by styfle** [comment]
Nice! What's normal dependencies? `dep`?

**Comment by styfle** [comment]
I just saw that the website says `dep`. https://badgen.now.sh/

Looks good and it loads faster than the original david-dm badge 🎉 
Representing on my readme here: https://github.com/styfle/packagephobia#readme

**Comment by amio** [comment]
Happily closed 😊
