### ISSUE TITLE
[idea] bare badge

### ISSUE THREAD

**Issue by amio** [amio/badgen-service#111]
1. What about a badge without left hand-side label? Like this one with whole blue background:
  ![fake bare badge example](https://badgen.net/badge//bare%20badge?icon=twitter)

2. The url could be:
    1. `/b/:status` - `b` stands for "bare" or shrunk "badge"
    2. `/bare/:status`
    3. other proposal

The idea comes from this [tweet](https://twitter.com/tusbar/status/1029068676920692736), will it be useful? Maybe use it for twitter badge or something, I think it would be better looking than current social badge.

Take a vote, 👍for useful, 👎for not useful, 😄🎉😕for url options 1/2/3.

**Comment by papb** [comment]
I don't see any problem, unless more and more badge options somehow cause the service to get slower (does this even make sense?)

**Comment by tusbar** [comment]
Removing the label is actually already doable by specifing an empty label!

e.g.: ![](https://badgen.net/circleci/github/tusbar/next-runtime-dotenv?icon=circleci&label) `/circleci/github/tusbar/next-runtime-dotenv?icon=circleci&label`

**Comment by amio** [comment]
Seems not too much demands for this feature. Close it for now, maybe review this in the future.
