### ISSUE TITLE
github open-issues badge showing "unknown"

### ISSUE THREAD

**Issue by papb** [amio/badgen-service#112]
Check the following badge:

https://badgen.net/github/open-issues/papb/better-promise-error-log

[![badge](https://badgen.net/github/open-issues/papb/better-promise-error-log)](https://badgen.net/github/open-issues/papb/better-promise-error-log)

It shows "github | unknown", instead of the expected "open issues | 0".

What could be causing this?

**Comment by papb** [comment]
Could it be because there are no issues at all on the repository (none open and none closed as well)?

**Comment by amio** [comment]
Oops, that's a bug 😅

**Comment by amio** [comment]
Should be fixed by now :D
