### ISSUE TITLE
Logo exploration

### ISSUE THREAD

**Issue by amio** [amio/badgen-service#114]
Some exploration on logo 🤗

## Title

![l1 title](https://user-images.githubusercontent.com/215282/44214670-4853e900-a1a3-11e8-8c23-76a0eb52a9e5.png)

![l2 title](https://user-images.githubusercontent.com/215282/44214710-599cf580-a1a3-11e8-851c-1c842ddc9b2b.png)

## Inline

![l1 line](https://user-images.githubusercontent.com/215282/44214796-87823a00-a1a3-11e8-802f-431a568b4cd8.png)

![l2 line](https://user-images.githubusercontent.com/215282/44214804-8fda7500-a1a3-11e8-80d1-6f6054b581ce.png)

**Comment by amio** [comment]
Final version. Thanks! @vinciarts 

![l1 title](https://user-images.githubusercontent.com/215282/44222612-af7b9880-a1b7-11e8-9e2a-ceaf02f9f5eb.png)

**Comment by olstenlarck** [comment]
It's awesome! : )) :tada:
