### ISSUE TITLE
Incomplete sanitization of text strings

### ISSUE THREAD

**Issue by samlanning** [amio/badgen-service#127]
[LGTM reports](https://lgtm.com/projects/g/amio/badgen-service/rev/61cfe58c68cd2f4acdd0027f2c1f8ef268969638) the following line does incomplete sanitization, introduced in 61cfe58.

https://github.com/amio/badgen-service/blob/8f703af7367d58670de39c2170a4e2949c382555/libs/serve-badge.js#L15

This line only replaces the first instance of `<`, which i'm guessing is not what you intended to do?

Would it not be better to handle this for both subject and status, and in the same way, making sure that any potential character which may mess up the SVG is escaped? (I forsee users wanting to e.g. use `<` or `>` characters to talk about version compatibility) This would probably be better handled in `badgen` than `badgen-service` right, so any other users of the library will also benefit.

**Comment by amio** [comment]
Since this text only occurs in `<text />` in svg, so replace `<` is good enough for fixing the problem.

I wish to keep these sanitization as simple as possible, to minimize the impact on performance. That's why I do this on `subject` but not `status`, in badgen-service (user land) other than badgen library.

**Comment by amio** [comment]
I made a test, sanitization on subject & status would cause ~20% perf drop for badgen =. =

**Comment by amio** [comment]
It turns out this should be handled in badgen, or the width would be calculated as `&lt;` other than `<`.

[Fixed](https://github.com/amio/badgen/commit/f847b98972e463a43300d670e0152de3a46e9f68) in badgen v2.4.4.

**Comment by samlanning** [comment]
Woah 20% drop is quite a bit... Did you use a benchmarking tool for this or was it just some simple tests?

> It turns out this should be handled in badgen, or the width would be calculated as &lt; other than <.

Ah yeah that would definitely be a problem, hmm.

**Comment by amio** [comment]
There's a benchmark suite in [badgen library](https://github.com/amio/badgen/#benchmarks)

**Comment by amio** [comment]
Fixed in 550a136
