### ISSUE TITLE
Support for npm downloads total

### ISSUE THREAD

**Issue by olstenlarck** [amio/badgen-service#13]
It seems it's missing.

````markdown
![](https://img.shields.io/npm/dt/react.svg)
````

badge: ![](https://img.shields.io/npm/dt/react.svg)

***

daaaamn, btw.. more often and more often Shields goes too slow.

**Comment by olstenlarck** [comment]
btw, i'm noticing some interesting things in the other downloads badges.

for example, it seems that `1250` downloads is shown as `1.25K/month`, which... is quite correct? Shields shows `1k/month`.

**Comment by amio** [comment]
Credits goes to [millify](https://www.npmjs.com/package/millify) 😄

**Comment by amio** [comment]
🤓
