### ISSUE TITLE
Consistent test coverage precision

### ISSUE THREAD

**Issue by GMartigny** [amio/badgen-service#134]
Across the different test code coverage report (coverall, codeclimate, codecov ...), there's some difference in how values are represented. Some truncate, other truncate with 1 decimals and some ... well, use plain value ...
![](https://badgen.net/codeclimate/coverage/GMartigny/pencil.js)

In my opinion, all percentage value (XX%) should all use the same rule. I would say, a rounded representation (36.666% => 37%) or rounded with one decimal (36.7%) are the most opinionated one.

**Comment by amio** [comment]
Usually codeclimate would provide the value at two decimals, not sure why this is not the case.

While anyway it's been fixed, all coverage have consistent precision now :D
