### ISSUE TITLE
Keybase badge

### ISSUE THREAD

**Issue by sindresorhus** [amio/badgen-service#140]
See: https://github.com/keybase/keybase-issues/issues/849 and https://github.com/badges/shields/issues/1299

Something like: ![image](https://user-images.githubusercontent.com/170270/45071242-905d9000-b0ff-11e8-8a6b-a44372d7ae67.png)

**Comment by amio** [comment]
It seems this example can be done with a static badge:
[![](https://badgen.net/badge/PGP/76CBE9A9/blue)](https://badgen.net/badge/PGP/76CBE9A9/blue)

I'm not familiar with keybase, is there some use case needs dynamic content on the badge?

**Comment by sindresorhus** [comment]
The PGP key can change.

**Comment by amio** [comment]
Use this
```
https://badgen.net/keybase/pgp/:username
```
to refer one's latest/current PGP key's fingerprint?

**Comment by sindresorhus** [comment]
👍

**Comment by lukechilds** [comment]
I would recommend using the 64-bit PGP fingerprint, 32-bit PGP fingerprint's are trivial to brute force: https://evil32.com

Something like:

<a title="Keybase" target="_blank" href="https://keybase.io/hyperdex">
  <img src="https://img.shields.io/badge/PGP-31DB%20EB37%20BF19%209A3C-green.svg">
</a>

**Comment by sindresorhus** [comment]
👍 I would still make the badge blue though. That green color is ugly.

**Comment by lukechilds** [comment]
Sure, I will submit a PR for this, should be super simple to add.

```js
const user = await fetch('https://keybase.io/_/api/1.0/user/lookup.json?usernames=hyperdex').then(res => res.json()).then(json => json.them[0]);
// `user` will be `null` if there is no matching user

const fingerprint = user.public_keys.primary.key_fingerprint;
const fingerprint64bit = fingerprint.substr(fingerprint.length - 16).toUpperCase().match(/.{1,4}/g).join(' ');
// 31DB EB37 BF19 9A3C
```

**Comment by amio** [comment]
🎉 It's live now https://badgen.net/#keybase
