### ISSUE TITLE
"packagephobia" badge label seems inconsistent

### ISSUE THREAD

**Issue by dougwilson** [amio/badgen-service#150]
It seems for the "packagephobia" badges, the label for the badge is "install size", but if there is no data for that npm module, the label instead changes to "packagephobia". I feel like the label should just always be "install size". Do you feel the same?

Example:

![body-parser](https://flat.badgen.net/packagephobia/install/compression)

vs

![csurf](https://flat.badgen.net/packagephobia/install/csurf)

**Comment by dougwilson** [comment]
Since it appears that the badge gets generated once it's been requested, my examples above are both working now. Here is a screenshot:

<img width="200" alt="screen shot 2018-09-08 at 19 29 37" src="https://user-images.githubusercontent.com/67512/45259543-a4beb880-b39d-11e8-8da1-d8ec3f33bd97.png">

**Comment by amio** [comment]
Can you provide a `packagephobia | unknown` badge url? @dougwilson 

If the request to packagephobia response 404, this badge would be `packagephobia | not found`, if it's timeout, the badge goes `packagephobia | timeout`, otherwise, it shows `packagephobia | unknown`.

I'm not sure what error occurs for that badge request.

**Comment by dougwilson** [comment]
All of those badges work now. They only show unknown for a short amount of time. The OP has the second badge that was in the unknown state earlier.

**Comment by dougwilson** [comment]
Anyway, my question though is why would the label be "packagephobia" when it is in error but otherwise "install size"? Should it not just say "install size" for the label even in error condition?

**Comment by amio** [comment]
By default we catch all kinds of possible errors in live badge functions, some might occurs before generating badge label. I would like to keep the error handling as less as possible for live functions, make it simple for creating live badge, the trade-off is error message would be more general (the error catcher didn't know the logic inside a live badge function).

For your use case, I think you may use `?label=install%20size` for a consistent label no matter what the default value is.
