### ISSUE TITLE
Zeit Deployment Badge

### ISSUE THREAD

**Issue by styfle** [amio/badgen-service#171]
It seems that zeit now is going to start [competing with CI](https://zeit.co/blog/now-ci) tools like travis, etc.

It might make sense to have a zeit badge that checks if the deployment succeeded or failed.

I haven't spent any time looking at the zeit API so maybe it's not possible, but I'm just throwing out an idea 😄

**Comment by tunnckoCore** [comment]
It's enough to have a status badge which I implemented in #158.

Ii seems like it starts competing but is too (like, too too) slow for now.

**Comment by styfle** [comment]
Oh yeah, the github status badge should work assuming now other checks are used on the repo.

**Comment by tunnckoCore** [comment]
Yea. Maybe implementing what we commented there (badge for each separate status) may be enough for what you meant with this issue.
