### ISSUE TITLE
Badge for “awesome” lists?

### ISSUE THREAD

**Issue by brandonweiss** [amio/badgen-service#176]
Any interest in adding a badge for “awesome” lists? It looks like this:

![](https://camo.githubusercontent.com/1997c7e760b163a61aba3a2c98f21be8c524be29/68747470733a2f2f617765736f6d652e72652f62616467652e737667)

People add it to their repos when their project has been included in an “awesome” list, like [awesome-nodejs](https://github.com/sindresorhus/awesome-nodejs).

**Comment by styfle** [comment]
The left side has a color and the font is a little different.

Compare these two:

https://awesome.re/badge.svg

https://badgen.net/badge//awesome?icon=travis&color=494368

**Comment by brandonweiss** [comment]
@styfle Yeah, the design is slightly different, so it wouldn’t necessarily be possible to replicate it entirely.

Without any modifications, this is probably the closest we could get.

![](https://badgen.net/badge/👓/awesome?color=494368)

The glasses are a bit hard to see, though. The next best thing might be if the real glasses icon was inverted to white and included as an `icon` that can be selected.

**Comment by amio** [comment]
Awesome icon added 😎

[![](https://badgen.net/badge//awesome/FC60A8?icon=awesome)](https://badgen.net/badge//awesome/FC60A8?icon=awesome)

**Comment by amio** [comment]
![sin city elijah wood 1920x1080 wallpaper_www wallpapername com_12](https://user-images.githubusercontent.com/215282/46932468-8164e880-d082-11e8-86c8-1cd4fab6c33c.jpg)

**Comment by tunnckoCore** [comment]
https://badgen.net/badge//AWESOME?icon=awesome&color=494368

![](https://badgen.net/badge//AWESOME?icon=awesome&color=494368)

**Comment by brandonweiss** [comment]
@amio Thanks!

![cheers](https://user-images.githubusercontent.com/4727/46966335-4c489e00-d062-11e8-862a-81c48c4d9545.gif)
