### ISSUE TITLE
XO badge improvements

### ISSUE THREAD

**Issue by sindresorhus** [amio/badgen-service#177]
Cool that you have an XO badge: https://badgen.net/#xo 👌

For the status badge, when it's enabled, it shows as `xo | enabled`. Would be nicer to show it as `xo | linter` or `xo | code style`, maybe even in the other direction: `linter | xo`.

The status example is currently using a project that is not using XO. Would be better to show how it looks like when enabled. `/xo/status/badgen` => `/xo/status/chalk`.

**Comment by bokub** [comment]
Why not **`xo | not enabled`** & **`code style | XO`** so when it's enabled, it looks like the badge in [XO's readme](https://github.com/xojs/xo#badge)?

**Comment by amio** [comment]
Hmmm, it seems fine to me now 😄
