### ISSUE TITLE
Bump chrome-webstore to version 1.2.1

### ISSUE THREAD

**Issue by simov** [amio/badgen-service#178]
:wave: 

You have to:

```
npm update chrome-webstore
```

From time to time the Google team updates their [REST API version](https://github.com/simov/chrome-webstore/commit/934cb0e66acda2c050fed869419a429ce06fc1c8). You can read more about it [here](https://github.com/simov/chrome-webstore#chrome-web-store-api-version).

**Comment by amio** [comment]
Sure & thanks!
I'll merge #179 for this :D
