### ISSUE TITLE
Azure Pipelines support

### ISSUE THREAD

**Issue by g-plane** [amio/badgen-service#200]
Will this service supports Azure Pipelines? More and more GitHub repositories use Azure Pipelines now, such as Yarn and TypeScript.

**Comment by amio** [comment]
That would be nice to have. 

I'm not familiar with Azure Pipelines, should we present some info from [this api](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-5.0)? Could you provide some example of possible badges? @g-plane

**Comment by g-plane** [comment]
I have checked the source code of Shields.io (https://github.com/badges/shields/blob/master/services/azure-devops/azure-devops-helpers.js), and there is a link: https://docs.microsoft.com/zh-cn/rest/api/azure/devops/build/Status/Get?view=azure-devops-rest-5.0

**Comment by amio** [comment]
We can start from this, thanks! @g-plane
