### ISSUE TITLE
Add support for # of twitter followers

### ISSUE THREAD

**Issue by styfle** [amio/badgen-service#206]
This is a feature of shields that would be good to have for badgen.

https://img.shields.io/twitter/follow/styfle.svg?label=Follow

![twitter](https://img.shields.io/twitter/follow/styfle.svg?label=Follow)

**Comment by amio** [comment]
Nice, will it be better with label "follower"?

**Comment by styfle** [comment]
Probably the best default label is "Twitter" or the person's username like `@styfle`.

My example above is using the verb "Follow" as in "Follow me on twitter by click here".

Another alternative is the noun "Followers" since it describes what the number represents as in "I have 483 followers on twitter".

The default at shields is a little longer: ![follow](https://img.shields.io/twitter/follow/styfle.svg)

**Comment by amio** [comment]
Hmm, I prefer to use shields' longer description as default label, for most complete description shown as example. Then let user specify it if they want a shorter label.

**Comment by styfle** [comment]
Cool, thanks!
