### ISSUE TITLE
No label layout

### ISSUE THREAD

**Issue by szmarczak** [amio/badgen-service#211]
### Actual layout

![image](https://user-images.githubusercontent.com/36894700/50166175-c9a0c100-02e6-11e9-852b-ab99f82cd346.png)

### Expected layout

![image](https://user-images.githubusercontent.com/36894700/50166289-0967a880-02e7-11e9-83f7-6798c882e009.png)

I think it would be nice to have that :D

**Comment by tunnckoCore** [comment]
Agree.

**Comment by amio** [comment]
Explored this idea before (#111), would a icon-only label fits your needs?

**Comment by szmarczak** [comment]
Yeah. But no label layout would be very useful for comparison tables, like [this one](https://github.com/sindresorhus/got/blob/master/readme.md#comparison). It would save some space for more columns :)

**Comment by amio** [comment]
Hmm, let's do it :D

**Comment by amio** [comment]
Landed. Add a param `?label` to the end of url:

![](https://badgen.net/npm/v/express?label)
https://badgen.net/npm/v/express?label

**Comment by szmarczak** [comment]
Thank you very much :heart:

**Comment by szmarczak** [comment]
The [HTTP lib comparison](https://github.com/sindresorhus/got/blob/master/readme.md#comparison) looks more clear now :D

**Comment by tunnckoCore** [comment]
Seems like it doesn't work when we have `icon`. :P Would be cool to support this too.

![](https://badgen.net/badge/foo/BAR/red?label=&icon=circleci)

**Comment by amio** [comment]
I think the current visual looks good already :D

What do you mean by "invert the color of svg"?

**Comment by amio** [comment]
I guess there would be more "want" than "need" :D

I'm not against this anyway, just put it on badgen's todo list. ✅
