### ISSUE TITLE
packagephobia badges trim decimal place

### ISSUE THREAD

**Issue by shellscape** [amio/badgen-service#215]
The packagephobia badges are trimming a decimal place. While this may seem trivial, in certain contexts (as in displaying and comparing install sizes against multiple packages) the actual, unmodified size of the install is desired.

Example: https://packagephobia.now.sh/result?p=webpack-plugin-serve ~ 5.84MB

![badge](https://badgen.net/packagephobia/install/webpack-plugin-serve) displays 5.8 MB.

I'd love to see the ability to display sizes as they come from packagephobia, unaltered.

**Comment by styfle** [comment]
I think this is a better request for [badgen](https://github.com/amio/badgen-service) since Package Phobia defers to it for badge rendering.

/cc @amio

**Comment by shellscape** [comment]
@styfle I created this issue in amio/badgen-service 😄

**Comment by styfle** [comment]
Hahahaha, I must have had a long day 😆 
Sorry about the confusion...this is the correct place for the issue.
I'll delete my post 😅

**Comment by amio** [comment]
Fix is landed now :D

**Comment by shellscape** [comment]
Thanks for jumping on that so quickly!
