### ISSUE TITLE
Support for Discord, YouTube, and Reddit

### ISSUE THREAD

**Issue by SpaceboyRoss01** [amio/badgen-service#219]
Discord, YouTube, and Reddit badges would be nice.

**Comment by tunnckoCore** [comment]
What should look like?

**Comment by SpaceboyRoss01** [comment]
Discord - member countYouTube - sub count/vid count/view countReddit - sub count

**Comment by amio** [comment]
Nice to have, @SpaceboyRoss01 PR's welcome! Or you can post related api here, that helps too :D
