### ISSUE TITLE
Problem with the npm downloads/day

### ISSUE THREAD

**Issue by olstenlarck** [amio/badgen-service#22]
It's always, or mostly always, a zero.

Probably we should use the `/range` for the previous day, not for the current one. 

I can dig what Shields does, but probably is that - for the previous day.

That's problem with the API actually:
https://api.npmjs.org/downloads/point/last-day/react

In most of the time it will show 0, i assume.

**Comment by olstenlarck** [comment]
I don't know what time is based the API, but here at UTC + 2 on 20th July, it still does not shows 19th July. So, we should move 2 days backwards to get it.

**Comment by amio** [comment]
Yea, this little bug bothered me weeks, thanks!
