### ISSUE TITLE
How to support badgen?

### ISSUE THREAD

**Issue by sloria** [amio/badgen-service#223]
Great work on badgen! I'm using it in most of my projects at this point.

Do you have a way to receive donations? I would like to help sustain the project.

**Comment by sloria** [comment]
Btw, if you decide to use [Open Collective](https://opencollective.com/), I've got you started: https://opencollective.com/badgen

**Comment by amio** [comment]
@sloria Appreciate for your love & support! I guess it's time to start an open collective. 😊

**Comment by amio** [comment]
Achievement unlocked!  🎉🎉🎉
https://opencollective.com/badgen
