### ISSUE TITLE
Badges say unknown on them

### ISSUE THREAD

**Issue by SpaceboyRoss01** [amio/badgen-service#229]
![image](https://user-images.githubusercontent.com/19699320/51865751-158a5100-22fc-11e9-8d19-4b4be4d8079e.png)

**Comment by bjankord** [comment]
Yeah, noticed this as well. A lot of badges seem to be displaying `unknown` on them.

Screenshot from doc site:
![badgen net_](https://user-images.githubusercontent.com/633148/51868759-5d1cd700-2314-11e9-8879-c817c2a9431b.png)

**Comment by amio** [comment]
Yep, guess it's related to this https://twitter.com/zeit_status/status/1089961390624755714

Created a new deployment to refresh caches, should be fine by now.

**Comment by styfle** [comment]
Looks like that fixed it

![image](https://user-images.githubusercontent.com/229881/51913915-a406dd00-23a5-11e9-94e9-7bdb19b3b12e.png)


https://screenshot-v2.now.sh/badgen.net?fullPage=true

**Comment by bjankord** [comment]
Yeah this looks resolved to me 👍

**Comment by SpaceboyRoss01** [comment]
Close #229

**Comment by leonardodino** [comment]
this error is back 😕

![Screen Shot 2019-04-23 at 5 39 08 AM](https://user-images.githubusercontent.com/8649362/56566928-2e687280-658a-11e9-9e42-46e57a04a546.png)

**Comment by amio** [comment]
Looks like we are hitting rate limit 🤔

**Comment by amio** [comment]
It's not rate limited, only half quota used. And the api works fine now, I'm not sure what caused that 😕

**Comment by styfle** [comment]
@amio You might try adding the `s-maxage` cache control header.

**Comment by amio** [comment]
@styfle The `s-maxage` header is added:
```
cache-control: public, max-age=60, stale-while-revalidate=604800, stale-if-error=604800, s-maxage=360
```
