### ISSUE TITLE
NuGet icon

### ISSUE THREAD

**Issue by viniciusjarina** [amio/badgen-service#236]
Would be nice to have  a NuGet package, just like the npm icon.
<img width="29" alt="screen shot 2019-02-03 at 9 55 31 pm" src="https://user-images.githubusercontent.com/926868/52188052-82bb4c00-27fe-11e9-98ac-9803207bd2a0.png">

**Comment by amio** [comment]
Thanks, we should add it to https://github.com/badgen/badgen-icons
