### ISSUE TITLE
Runkit Support

### ISSUE THREAD

**Issue by amio** [amio/badgen-service#24]
Live badge with data from a runkit endpoint.

### URL

`https://badgen.net/runkit/:endpoint_id/:params`

### Example Endpoint

RunKit Notebook: https://runkit.com/amio/peoples

[![](https://badgen.net/runkit/peoples-txwpy888xiuk/102909)](https://badgen.net/runkit/peoples-txwpy888xiuk/102909)

RunKit Notebook: https://runkit.com/amio/satisfaction

[![](https://badgen.net/runkit/satisfaction-flq08o9mm3ka/102909/employee)](https://badgen.net/runkit/satisfaction-flq08o9mm3ka/102909/employee)
[![](https://badgen.net/runkit/satisfaction-flq08o9mm3ka/102909/people)](https://badgen.net/runkit/satisfaction-flq08o9mm3ka/102909/people)
[![](https://badgen.net/runkit/satisfaction-flq08o9mm3ka/102909/topic)](https://badgen.net/runkit/satisfaction-flq08o9mm3ka/102909/topic)

**Comment by olstenlarck** [comment]
btw, out of scope of this issue, but why you are not using `micro` and `micro-dev` here? I was thinking this last days..

**Comment by styfle** [comment]
This is a great idea! 🎉 

I have a list of many Online IDE's that are similar to Runkit that you might want to implement (assuming they have APIs available).

Check out the list here: https://github.com/styfle/awesome-online-ide

**Comment by styfle** [comment]
How about something like this:

https://badgen.net/https/peoples-x9okc2jt0paw.runkit.sh

Which would call this endpoint:

https://peoples-x9okc2jt0paw.runkit.sh/

Then you can support any arbitrary https calls by looking for this pattern:

https://badgen.net/https/:url

**Comment by amio** [comment]
I thought about exactly the same thing too 😄

Will `/https/something.now.sh` looks a bit tricky? Looks like imitating https url but not really a https schema 🤔

**Comment by styfle** [comment]
I have seen this syntax used somewhere else but I can't remember.
I don't think it's confusing, heres how it will look:


![image](https://user-images.githubusercontent.com/229881/44098675-d25d194c-9fae-11e8-835b-9e5548fb31bf.png)

**Comment by amio** [comment]
Made a runkit doc page
https://badgen-service-aqroqbecxx.now.sh/docs/runkit

And put runkit link to a separate paragraph
https://badgen-service-aqroqbecxx.now.sh/#for-badge-makers

**Comment by styfle** [comment]
That `/https` endpoint is amazing 🔥
