### ISSUE TITLE
Bug in badges with scoped packages

### ISSUE THREAD

**Issue by olstenlarck** [amio/badgen-service#34]
Because the "workaround" https://github.com/amio/badgen-service/blob/master/libs/live-fns/npm.js#L96

It seems that `https://registry.npmjs.org/@babel%2Fcore/*` shows empty object
but removing the star shows all versions. 

proof: https://registry.npmjs.org/@babel%2Fcore

It's interesting why with `@nestjs/core/*` it still works :laughing:

**Comment by olstenlarck** [comment]
So.. it seems the api currently works as expected both for scoped and non-scoped ones?

So we can just request `registry.npmjs.org/[pkg-name]`

and get `dist-tag` field, and get version from there `dist-tag.latest` by default.

**Comment by olstenlarck** [comment]
AHA! Got it... `/latest` does not work for the scoped ones :D

**Comment by amio** [comment]
Weird, `@nestjs/core/*` stop working for me now 🤔

I used to [get latest from full meta list](https://github.com/amio/badgen-service/blob/920a4832f7eb4218d08ed446a230bc974ff4137f/libs/live-fns/npm.js#L37-L44), then turn to that tricky method(use `/*` to get latest only) to reduce response size, seems we need to go back again 🤨

**Comment by olstenlarck** [comment]
No problem, i'm working on that.

**Comment by olstenlarck** [comment]
The interesting thing in that API is that the problem is only when `/latest` otherwise it works for other tags like `/@nestjs/core/next` :laughing:

**Comment by olstenlarck** [comment]
Watafak `/next` gives me error, no matter what package (except scoped ones).. :rofl:

**Comment by amio** [comment]
😂npm registry:

![1488583772894](https://user-images.githubusercontent.com/215282/43188082-df9fc318-9025-11e8-8b0c-ba3a699812cc.jpg)

**Comment by olstenlarck** [comment]
hahaaha

**Comment by olstenlarck** [comment]
I don't know how some people build such APIs ;d

**Comment by olstenlarck** [comment]
Just realized, that if you want to get another tag, you just can do it with another endpoint, like it is able for the `latest` tag.

So in case we recieve different than `latest`, we will trigger the full metadata and get it from `dist-tags`...

**Comment by olstenlarck** [comment]
just a note for curious devs working with that api:

a) with scoped packages there is no /latest, but have /dist-tag-name
b) for not scoped ones is exactly the opposite - there IS /latest, but not have /dist-tag-name

pahahahaha

**Comment by amio** [comment]
👆 Should add this to knowledge base.
