### ISSUE TITLE
Support `suffix`, `query` and `uri` query params

### ISSUE THREAD

**Issue by olstenlarck** [amio/badgen-service#36]
Related to one answer in Reddit.

https://www.reddit.com/r/javascript/comments/91m0cn/badgen_fast_badge_generating_service_shieldsio/e2zje8w

SO: https://stackoverflow.com/questions/50122026/how-to-get-the-number-of-people-in-a-getsatisfaction-community-for-shields-io/50122101#50122101

---

The `suffix` is kinda good idea. But `uri` may be a bit more complex.

- `uri` is for replacing the request endpoint, for example, to npm API
- `query` is for selecting things from the return by `uri` data
- `suffix` is value appeded to the right side of the badge

**Comment by amio** [comment]
Hmmm, more use case are coming 😋

I think there's more than one way to achieve the goal: __serve badge image base on any json source__:

1. The `uri`/`query`/`suffix` way, which is used on shields.io

2. Support reading result from RunKit endpoint, let RunKit scripts ([example](https://runkit.com/amio/hello-badgen)) do the dirty works, leave the url clean & readable as:
    ```
    https://badgen.net/runkit/hello-badgen/:arg1/:arg2
    ```

3. Use RunKit endpoint to response a 302 redirection to [static badge address](`https://badgen.net/badge/community/1111%20members/green`), like https://packagephobia.now.sh does right now.

Both (2) and (3) have these benefits:
- Clean & readable url
- Read from more complex api source
- Leverage the power of whole npm (thanks to RunKit) 🤯

**Comment by amio** [comment]
A roughly support for RunKit is online now:

### Examples

RunKit Notebook: https://runkit.com/amio/peoples

[![](https://badgen.net/runkit/amio/peoples/102909)](https://badgen.net/runkit/amio/peoples/102909)

RunKit Notebook: https://runkit.com/amio/satisfaction

[![](https://badgen.net/runkit/amio/satisfaction/102909/employee)](https://badgen.net/runkit/amio/satisfaction/102909/employee)
[![](https://badgen.net/runkit/amio/satisfaction/102909/people)](https://badgen.net/runkit/amio/satisfaction/102909/people)
[![](https://badgen.net/runkit/amio/satisfaction/102909/topic)](https://badgen.net/runkit/amio/satisfaction/102909/topic)

**Comment by olstenlarck** [comment]
Yup. Make sense. Let's be a bit different. :)

Absolutely awesome! :tada: With a bit of documentation would be great.

**Comment by amio** [comment]
Since [RunKit endpoint support](https://github.com/amio/badgen-service/issues/24) could cover this requirement, no plan to support this recently.
