### ISSUE TITLE
Rename/consistency for CIs - Circle, Travis,  AppVeyor

### ISSUE THREAD

**Issue by olstenlarck** [amio/badgen-service#37]
For consistency, i think it would be good all of the CIs to be `build | passing` or `build | success`, or every CI to have label its name, or every CI badge to be same, except icons

- CircleCI ![](https://badgen.net/badge/build/passing/green?icon=circleci) or ![](https://badgen.net/badge/circleci/passing/green)
- TravisCI ![](https://badgen.net/badge/build/passing/green?icon=travis) or ![](https://badgen.net/badge/travis/passing/green)
- AppVeyorCI ![](https://badgen.net/badge/build/passing/green?icon=appveyor) or ![](https://badgen.net/badge/appveyor/passing/green)

Always dreamed about that :laughing: 

Would be awesoome if they include icons by default and be `build | passing`.

Hm. What about "icon style" at `icon.badgen.net`? So all badges will have their respective icons (if they have). How cool is that ![](https://badgen.net/github/release/olstenlarck/xaxa?icon=github) (btw, should add white icons too ;d)

**Comment by olstenlarck** [comment]
btw, did you noticed that there is a bit more right padding than left padding in the label side,when there is icon? or it is only on phone, hm.

**Comment by amio** [comment]
- default icon
  Better let user to choose if they want icon within. We could provide icon examples in the index page, hinting user to use it freely.

- status consistency
  Nice to have, we need to count all possible status from all 3 CI(and more will comming), to know for sure if this consistency works flawlessly.

- Colored icon
  I'm planning modify every non-white icon to white :D We don't provide 'social-style' badge, no need for those non-white icons.

**Comment by olstenlarck** [comment]
> Sharp eyes! +1 Need more tweaks on badgen yum

It's only on mobile. Android v7 i believe, not sure.

**Comment by olstenlarck** [comment]
It's convention to be `build | passing`, but but also it's a good thing to be able to differentiate  without hovering the badge to see what is the actual link behind it and which is the CI. That's why i'm for icons by default for the CIs.

**Comment by olstenlarck** [comment]
Oooh, i got what you meant with 2nd bullet. Right.

**Comment by amio** [comment]
> it's a good thing to be able to differentiate without hovering the badge to see what is the actual link behind it and which is the CI.

Totally agree! We could change label to CI name, keep their status as it is right now.

**Comment by olstenlarck** [comment]
CircleCI

```
// :retried, :canceled, :infrastructure_fail, :timedout,
// :not_run, :running, :failed, :queued, :scheduled,
// :not_running, :no_tests, :fixed, :success
"status" : "success", 
```

TravisCI - damn, this guys are really bad in APIs and any other case ;d

Seems like they are few `passed`, `failed`, `errored` in `build.state`
https://docs.travis-ci.com/api/?http#builds
If there is no such repo or account, `builds` is empty array, so we can set `unknown`.

> keep their status as it is right now.

Naah. Where goes the consistency ;d

**Comment by olstenlarck** [comment]
> keep their status as it is right now.

Or at least, if build is okey, show `passing` for all, otherwise their respective term for error/fail/unknown/running/quequed/timeout and etc.

**Comment by amio** [comment]
BTW, the icon color issue has been fixed in https://github.com/amio/badgen-service/commit/55970a895d56e96871886d73a41e003bc31050be#diff-3c6d535456832f7a3a673a4265007624R18
![](https://badgen.net/badge/github/v1.2.3?icon=github)
