### ISSUE TITLE
Pass request object as 1st argument to each live badge function

### ISSUE THREAD

**Issue by olstenlarck** [amio/badgen-service#39]
This will allow more flexibility and users of the RunKit will be able to access whatever they need. For example, getting `req.path` parsing it and getting queryparams so depending on some params, to base some logic.

For builtin ones, this will allow for listening on the `registry_uri`, for example, in the npm live badge. No need to have global support (inside all live badges) for this or such query params. Even can be more, for example in the npm default export it will be passed only to the `/npm/v` endpoint, so no security or such issues.

So

```js
module.exports = async function npm (req, method, ...args) {
  switch (method) {
    case 'v':
      return version(req, args)
    case 'dt':
      return download('total', args)
  }
  // code ...
}

async function version (req, args) {
  const registry = qs.parse(req.path, true).registry_uri || 'registry.npmjs.org'

  // code ...
}
```

So nor other npm endpoints, nor other live badges will have access to that registry_uri query param, it just won't matter.

**Comment by amio** [comment]
This could be useful for RunKit live-fn, but I'm not sure if it's a must-have.

For npm, why do you want to let user customize `registry_uri`?

**Comment by amio** [comment]
I think this is not quite needed, close issue for now. Feel free to reopen if you have further idea on this 🤗
