### ISSUE TITLE
travis redirect build unknown

### ISSUE THREAD

**Issue by styfle** [amio/badgen-service#4]
I have a repo: https://github.com/styfle/packagephobia

I tried visiting https://badgen.now.sh/travis/styfle/packagephobia which redirects to https://api.travis-ci.com/styfle/packagephobia.svg?branch=master but that shows "build unknown".

My readme is currently using https://travis-ci.org/styfle/packagephobia.svg?branch=master which redirects to https://api.travis-ci.org/styfle/packagephobia.svg?branch=master and this correctly hows "build passing"

Note the difference here is `.com` vs `.org`.

**Comment by amio** [comment]
hmm, travis is in the process of [migrating .org repos to .com](https://docs.travis-ci.com/user/open-source-on-travis-ci-com/), but seems not so seamlessly.

What about adding a `/travis-org/styfle/packagephobia` for repos on travis-ci.org?

**Comment by amio** [comment]
![https://badgen-service-oksomisius.now.sh/travis-org/styfle/packagephobia](https://badgen-service-oksomisius.now.sh/travis-org/styfle/packagephobia)
https://badgen-service-oksomisius.now.sh/travis-org/styfle/packagephobia

**Comment by styfle** [comment]
That might work but it's kind of confusing to the end user because I don't remember off the top of my head if I am using .com or .org and which one is the open source offering. I'll probably just stick with what I have until travis finishes migrating. https://travis-ci.org/styfle/packagephobia.svg?branch=master

**Comment by amio** [comment]
Sure, I'm not so satisfy with this solution either, it's a compromise(better than others comming to my mind).

It looks we can hardly get over the difference between travis .com & .org. If travis could do a 302 redirection between com & org, that would be the best solution. 😅

**Comment by styfle** [comment]
This appears to be fixed now 😄
