### ISSUE TITLE
Doc page for live badges

### ISSUE THREAD

**Issue by amio** [amio/badgen-service#41]
Finally start building docs for live badges 👻

Starting from packagephobia https://badgen.net/docs/packagephobia

![djce55qvsaehrji](https://user-images.githubusercontent.com/215282/43269987-9cb479de-9126-11e8-916b-cbdf67876d0d.jpg)

**Comment by olstenlarck** [comment]
Why? :laughing: It's so easy and obvious from the index.

**Comment by amio** [comment]
Some live badge (might) has more than 3 param segments, may need a explanation for every segment's purpose, "Don't make me think ™".

But yeah, maybe no need for every one 😆
New index page already clearer than old one.

**Comment by olstenlarck** [comment]
Cool. It's live now. ;D
