### ISSUE TITLE
Uptime Robot examples have misspelled "lasy-day"

### ISSUE THREAD

**Issue by rmccue** [amio/badgen-service#44]
The Uptime Robot badges incorrectly have `lasy-day`, e.g. `/uptime-robot/lasy-day/m780731617-a9e038618dc1aee36a44c4af`

This is incorrect, and gives unknown topic:

<img src="https://badgen.net/uptime-robot/lasy-day/m780731617-a9e038618dc1aee36a44c4af" />

It should instead have `day`:

<img src="https://badgen.net/uptime-robot/day/m780731617-a9e038618dc1aee36a44c4af" />

**Comment by amio** [comment]
Yeap, a mistake 😅

Fixed now. Thanks!
