### ISSUE TITLE
Patreon Logo svg

### ISSUE THREAD

**Issue by olstenlarck** [amio/badgen-service#48]
Can we think for adjust it to our needs?

https://www.vectorlogo.zone/logos/patreon/patreon-ar21.svg

I'm not on SVGs too much. ;d We can only get the "P" one, but should somehow invert the colors. Actually... the orange should be white and and the rest transparent?

**Comment by amio** [comment]
Seems they have redesigned a new logo, we can get it here https://simpleicons.org/?q=patreon

**Comment by olstenlarck** [comment]
Oooh! Cool, that's a lot better.
