### ISSUE TITLE
Bug in OpenCollective badges

### ISSUE THREAD

**Issue by olstenlarck** [amio/badgen-service#55]
It shows (1,967,277.00) but it is 19,672.77 and same for the yearly income.

![2018-08-01-19 10 04_1280x1024_scrot](https://user-images.githubusercontent.com/5038030/43533887-96b1077c-95be-11e8-899d-cad101e298f6.png)

but it is a lot smaller ;d

![2018-08-01-19 10 17_1280x1024_scrot](https://user-images.githubusercontent.com/5038030/43533897-9f4ab5d6-95be-11e8-92cd-b54cda43727b.png)

**Comment by amio** [comment]
Oops, thanks!

**Comment by amio** [comment]
It's live now https://badgen.net/#opencollective

**Comment by olstenlarck** [comment]
Closing. :P
