### ISSUE TITLE
[flat.badgen.net] Usage example alignment

### ISSUE THREAD

**Issue by RedSparr0w** [amio/badgen-service#57]
`badgen.net:`
![image](https://user-images.githubusercontent.com/7288322/43551250-82cc7dc8-963a-11e8-83b2-18c49af9e6d7.png)

`flat.badgen.net:`
![image](https://user-images.githubusercontent.com/7288322/43551235-6ce0af7a-963a-11e8-812c-4024f3edc90f.png)
Looks like it needs an additional 5 spaces at the beggining of each line (excl the first line) to cover the `flat.`
![image](https://user-images.githubusercontent.com/7288322/43551366-da5ec9d8-963a-11e8-805c-4d174fea51d6.png)

**Comment by amio** [comment]
Hmm, a regex is broken.

**Comment by amio** [comment]
That regex has been moved from string to `<script />` block, should get rid of those escaping character.

Fixed right now https://flat.badgen.net

Thanks!
