### ISSUE TITLE
Cache is too long?

### ISSUE THREAD

**Issue by olstenlarck** [amio/badgen-service#58]
Pretty much.. After the last changes related to the cache, it started to feels.

I sometimes am forced to visit the badgen badge url to trigger refresh.
Not to mention this not always works ;d

Even with F5, even with CTRL+R, even with another browser - nothing.

**Comment by amio** [comment]
Hmm, did you mean this(87edb71773054915050fb0960d654e7a05337e3a) change?

**Comment by olstenlarck** [comment]
Probably. I'm not usre.

**Comment by amio** [comment]
Reduced the update delay to 1~2 minutes, see if it get better?

**Comment by olstenlarck** [comment]
Hm. Actually, bigger is better, but only decrease it in CloudFlare.


Anyway, i'll see soon.

**Comment by amio** [comment]
@olstenlarck Is this problem solved?

**Comment by olstenlarck** [comment]
yea
