### ISSUE TITLE
Feature request: social badges

### ISSUE THREAD

**Issue by quietshu** [amio/badgen-service#61]
For example:  
![](https://img.shields.io/twitter/url/http/shields.io.svg?style=social)

More: https://shields.io/#/examples/social

**Comment by olstenlarck** [comment]
What about `socialen.net` for them? :laughing: :rocket:

**Comment by amio** [comment]
@olstenlarck What's `socialen.net`?

**Comment by olstenlarck** [comment]
Future home of those social badges? :D :D

**Comment by amio** [comment]
😂

**Comment by amio** [comment]
Personally, I'm not very satisfy with current "social badge" design, maybe we could have some experiment on it's looking, before landing this feature.

**Comment by GMartigny** [comment]
Why not using the same design as other badges ?

![Twitter](https://badgen.net/badge//@badgen_net/009EEF?icon=twitter)![Github](https://badgen.net/badge//amio/282D31?icon=github)
or
![Twitter](https://badgen.net/badge/twitter/@badgen_net/009EEF?icon=twitter)![Github](https://badgen.net/badge/github/amio/282D31?icon=github)

With a short URL like:
https://badgen.net/twitter/badgen_net
https://badgen.net/github/amio

**Comment by olstenlarck** [comment]
Yup, i'm agree.

**Comment by amio** [comment]
> With a short URL like:
https://badgen.net/twitter/badgen_net
https://badgen.net/github/amio

This shorten url are handy but may conflict with live badge url, this could be better:
```
https://badgen.net/icon/:icon-name/:subject/:status
```
but that's not too much difference with:
```
https://badgen.net/badge/:subject/:status?icon=:icon-name
```

**Comment by amio** [comment]
@GMartigny 's example is good enough that I think we don't need another social badge style:

[![Twitter](https://badgen.net/badge//@badgen_net/009EEF?icon=twitter)](https://badgen.net/badge//@badgen_net/009EEF?icon=twitter) [![Github](https://badgen.net/badge//amio/333?icon=github)](https://badgen.net/badge//amio/333?icon=github)
