### ISSUE TITLE
GitHub badges get rate limited

### ISSUE THREAD

**Issue by tusbar** [amio/badgen-service#68]
<img width="646" alt="screen shot 2018-08-03 at 9 06 51 pm" src="https://user-images.githubusercontent.com/166147/43661078-2facd67e-9761-11e8-8a54-1c79b2022f55.png">

**Comment by amio** [comment]
This can be problematic 🤔
Maybe we can add an api/cache layer to release some load from service provider, and having better cache control.

**Comment by tusbar** [comment]
I guess badgen.net could also authenticate GitHub API requests.

**Comment by amio** [comment]
5000/hour quota now 🎉

https://api.badgen.net/_stats

**Comment by tusbar** [comment]
Nice! 👍
