### ISSUE TITLE
Badge to show dependents of a npm package

### ISSUE THREAD

**Issue by sindresorhus** [amio/badgen-service#69]
Would be nice to have a badge to show off how many npm packages depend on my package. For example, the `1717 Dependents` number at https://www.npmjs.com/package/got.

You could either:
- Use the API. Example: https://github.com/chrisdickinson/npm-get-dependents
- Scrape. Example: https://github.com/astur/check-npm-dependents

**Comment by amio** [comment]
Awesome, nice to have!

**Comment by amio** [comment]
It's live now :D
[![](https://badgen.net/npm/dependents/got)](https://badgen.net/npm/dependents/got)

**Comment by amio** [comment]
And an api for dependents https://api.badgen.net/npm/dependents/got 🏂

**Comment by sindresorhus** [comment]
Nice! Thanks for the super-fast turnaround 🙌

Using it here now: https://github.com/chalk/chalk
