### ISSUE TITLE
How to get uptime robot ID?

### ISSUE THREAD

**Issue by bokub** [amio/badgen-service#70]
I see that the URI for the uptime of **badgen-service** is 
> https://badgen.net/uptime-robot/day/m780731617-a9e038618dc1aee36a44c4af

How to find the ID at the end of the URI ? I cannot find it from the stats page, which is https://stats.uptimerobot.com/z6nqBfYGB

Thanks for your help

**Comment by amio** [comment]
It's not so intuitive, you can go to "My Settings -> Monitor-Specific API Keys", search for a monitor, then create an api key for that monitor.

![image](https://user-images.githubusercontent.com/215282/43676313-547a5c5e-9821-11e8-81d9-1e2f6b67e821.png)

**Comment by bokub** [comment]
Thanks a lot. :+1:
I think it would be nice to have a question mark icon with a tooltip on the examples page

**Comment by amio** [comment]
Yup, may need a doc page like https://badgen.net/docs/packagephobia

**Comment by bokub** [comment]
All right, I'll write one 📖
