### ISSUE TITLE
Update semver colors for -dev

### ISSUE THREAD

**Issue by tusbar** [amio/badgen-service#78]
![](https://badgen.net/packagist/v/monolog/monolog/latest)

Maybe introduce another color?

**Comment by amio** [comment]
This one can follows alpha/beta/canary/rc with cyan 😬

**Comment by tusbar** [comment]
`dev` is not really a release though, is it?

**Comment by amio** [comment]
Agree, if someone use it on release, I think they mean `canary` or `alpha` etc.

**Comment by amio** [comment]
Or take this

> dev is not really a release though

As the reason to keep it in blue (no opinion color)

**Comment by amio** [comment]
Made it cyan now :D
