### ISSUE TITLE
Badge to show dependents of a GitHub repo

### ISSUE THREAD

**Issue by sindresorhus** [amio/badgen-service#83]
The number you find here: https://github.com/chalk/chalk/network/dependents

GitHub has a GraphQL API endpoint for it: https://developer.github.com/changes/2018-04-24-preview-dependency-graph-and-vulnerability-hooks/

**Comment by amio** [comment]
This one can be useful. And ❤️❤️❤️ for API!

**Comment by amio** [comment]
Seems this api only provide manifest for [dependencies](https://developer.github.com/v4/object/dependencygraphmanifest/), but no dependents 😣

**Comment by amio** [comment]
We can still do this in an ugly way by scraping GitHub 😠

**Comment by amio** [comment]
Is this label (`repo dependents` / `pkg dependents`) ok?

![](https://badgen.net/github/dependents-repo/chalk/chalk)
https://badgen.net/github/dependents-repo/chalk/chalk

![](https://badgen.net/github/dependents-pkg/chalk/chalk)
https://badgen.net/github/dependents-pkg/chalk/chalk

**Comment by amio** [comment]
If current labels are fine, then this is complete now. :D

**Comment by sindresorhus** [comment]
Yes, looks good :)
