### ISSUE TITLE
Feature Request: Add hackage

### ISSUE THREAD

**Issue by madnight** [amio/badgen-service#92]
Maybe you could add hackage bagdes like shields io

**Comment by amio** [comment]
Good to have

**Comment by amio** [comment]
It's live now 🎉 https://badgen.net/#hackage

**Comment by madnight** [comment]
Wow, that was fast!  
Thank you, also in the name of the Haskell community : )

**Comment by Lysxia** [comment]
Thanks for this! Shouldn't the badge say "hackage" instead of "cabal"?

**Comment by amio** [comment]
Oops, sure! Fixed.
