### ISSUE TITLE
Coveralls branch percentage bug?

### ISSUE THREAD

**Issue by dougwilson** [amio/badgen-service#96]
I'm not sure if this is a bug in badgen or Coveralls API, but shields.io seems to be returning the expected 100% while badgen seems to be using a percentage from a recent PR.

Badgen URL: `https://flat.badgen.net/coveralls/c/github/expressjs/morgan/master`
shields.io URL: `https://img.shields.io/coveralls/expressjs/morgan/master.svg?style=flat-square`

Rendered:
Badgen: ![](https://flat.badgen.net/coveralls/c/github/expressjs/morgan/master)
shields.io: ![](https://img.shields.io/coveralls/expressjs/morgan/master.svg?style=flat-square)

**Comment by amio** [comment]
Hmm 🤔

For master branch, this api 
https://coveralls.io/github/expressjs/morgan.json?branch=master returns 99.13 (right now),

And the "default" endopoint:
https://coveralls.io/github/expressjs/morgan.json returns 99.15 (right now)

**Comment by dougwilson** [comment]
I mostly expected it was going tot be a bug in the Coveralls API. Not sure how shields.io is getting 100% (it's possible they have it cached maybe -- though the build the lower % is from is quite old so 🤷‍♂️ ).

Thanks for taking a look @amio

**Comment by amio** [comment]
I think what they do is getting the result of coveralls.io's default badge data.

coveralls.io use redirection for performance (no need to generate badge svg on the fly), then shields.io read the `Location` header for faster result.

**Comment by amio** [comment]
coveralls.io's "official" badge shows `coverage | 100%` while their [page](https://coveralls.io/github/expressjs/morgan) reporting `COVERAGE DECREASED (-0.4%) TO 99.138%` 😅

![image](https://user-images.githubusercontent.com/215282/43937738-0d2e605a-9c92-11e8-882c-e938d6714603.png)

**Comment by dougwilson** [comment]
Well, 100% is correct for master branch. The lower % you are seeing is from a pull request.

Using shields.io means that a badge will show coverage of repo code but switching to badgen.net with this bug means it will show whatever the most recent pr to the repo is instead it seems.

**Comment by amio** [comment]
Hmm, yes. If there's no api for that, I should use same method as shields.

**Comment by dougwilson** [comment]
This is amazing, thank you!

**Comment by olstenlarck** [comment]
Say it Coveralls, and don't hate it more. :rofl:

**Comment by amio** [comment]
What? Call it "coveralls" on label?

**Comment by olstenlarck** [comment]
No no.. :D Just trolling Coveralls, cuz always was not good.

**Comment by amio** [comment]
😂
